# Generated by Django 5.2.1 on 2025-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-09T20:27:14.010653+05:00', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-09T20:27:14.010653+05:00', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('jarayonda', 'Jarayonda'), ('tasdiqlandi', 'Tasdiqlandi'), ('bekor qilindi', 'Bekor qilindi'), ('yetkazildi', 'Yetkazildi')], default='jarayonda', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-09T20:27:14.010653+05:00', verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
