# Generated by Django 5.2.1 on 2025-06-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_received',
            field=models.FloatField(blank=True, null=True, verbose_name='Product price received'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('jarayonda', 'Jarayonda'), ('tasdiqlandi', 'Tasdiqlandi'), ('bekor qilindi', 'Bekor qilindi')], default='jarayonda', max_length=20, verbose_name='Status'),
        ),
    ]
