# Generated by Django 5.2.1 on 2025-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_price_received_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'verbose_name': 'Maxsulot tarixi', 'verbose_name_plural': 'Maxsulotlar tarixi'},
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='price_received',
            field=models.FloatField(blank=True, null=True, verbose_name='Product price received'),
        ),
    ]
