# Generated by Django 5.2.1 on 2025-06-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_producthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product category'),
        ),
    ]
