# Generated by Django 5.2.1 on 2025-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_producthistory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='status',
            field=models.CharField(choices=[('yaratildi', 'Yaratildi'), ("qo'shildi", "Qo'shildi"), ('ayrildi', 'Ayrildi')], default='yaratildi', max_length=20, verbose_name='Status'),
        ),
    ]
