# Generated by Django 5.2.1 on 2025-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_telegram_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
    ]
